### ISSUE TITLE
checkstyle toolVersion not picked up?

### ISSUE THREAD

**Issue by pazz** [cs125-illinois/gradlegrader#3]
Running this plugin via the "old" buildscript gradle configuration seems to be incompatible with recent checkstyle gradle config.

I have explicitly set the toolVersion for the checkstyle plugin in order to make it work with the vanilla [google_ckecks.xml checkstyle config]https://checkstyle.sourceforge.io/google_style.html),
because per default, gradle (6.4) picks a checkstlye version incompatible with their own xml.

This (`gradle checkstyleMain`) works as expected with this config, but the gradlegrader plugin chokes on it. Is it perhaps defaulting to an old version of checkstyle?

`build.gradle`:
```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.github.cs125-illinois:gradlegrader:2020.1.0'
    }
}
apply plugin: 'java'
apply plugin: 'application'
apply plugin: 'checkstyle'
apply plugin: 'edu.illinois.cs.cs125.gradlegrader'

repositories {
	mavenCentral()
}

dependencies {
	testImplementation('org.junit.jupiter:junit-jupiter:5.6.0')
	testImplementation('com.github.cs125-illinois:gradlegrader:2020.1.0')
        implementation('com.github.cs125-illinois:gradlegrader:2020.1.0')
}

test {
	useJUnitPlatform()
	testLogging {
		events "passed", "skipped", "failed"
	}
}


checkstyle {
    toolVersion = '8.32'  // assign the latest checkstyle version explicitly
    showViolations = false
}
tasks.withType(Checkstyle) {
    reports {
        xml.enabled true
        html.enabled false
    }
}
gradlegrader {
    assignment 'Spring2019.MP0'
    checkstyle {
        points = 10
        configFile = file('config/checkstyle/checkstyle.xml')
    }
    identification {
        txtFile = file('email.txt')
        validate = { email -> email.endsWith('@liverpool.ac.uk') }
    }
    reporting {
        jsonFile = file('grade.json')
        post {
            endpoint = "https://example.com/progress"
        }
        printPretty {
            title = "MP0: Location"
            notes = "Note that the maximum local grade is 90/100. 10 points will be awarded during " +
                    "official grading if you have submitted code that earns at least 40 points by " +
                    "Monday, May 20."
        }
    }

application {
    mainClassName = 'uk.ac.liverpool.comp122.week1.HelloJava'
}
}
```

Successful checkstyle invocation
```terminal
./gradlew clean checkstyleMain

> Task :checkstyleMain
Checkstyle rule violations were found. See the report at: file:///home/pazz/repo/teaching/2021-COMP122/templates/Assignment/build/reports/checkstyle/main.xml
Checkstyle files with violations: 1
Checkstyle violations by severity: [warning:1]


BUILD SUCCESSFUL in 2s
3 actionable tasks: 3 executed
```

Failing autograder:
```terminal
 ./gradlew grade               

> Task :relentlessCheckstyle
Checkstyle crashed: : Unable to create Root Module: config {/home/pazz/repo/teaching/2021-COMP122/templates/Assignment/config/checkstyle/checkstyle.xml}, classpath {null}.
        at com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask.createRootModule(CheckstyleAntTask.java:415)
        at com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask.realExecute(CheckstyleAntTask.java:305)
        at com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask.execute(CheckstyleAntTask.java:288)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
        at groovy.util.AntBuilder.performTask(AntBuilder.java:333)
        at groovy.util.AntBuilder.nodeCompleted(AntBuilder.java:278)
        at org.gradle.api.internal.project.ant.BasicAntBuilder.nodeCompleted(BasicAntBuilder.java:80)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:483)
...
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:78)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:75)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:75)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:63)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:82)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:52)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module LineLength - Property 'fileExtensions' does not exist, please check the documentation
        at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:473)
        at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:198)
        at com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask.createRootModule(CheckstyleAntTask.java:412)
        ... 243 more
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Property 'fileExtensions' does not exist, please check the documentation
        at com.puppycrawl.tools.checkstyle.api.AutomaticBean.tryCopyProperty(AutomaticBean.java:223)
        at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:191)
        at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:468)
        ... 245 more
The message received from the daemon indicates that the daemon has disappeared.
Build request sent: Build{id=1ec55c8a-24f4-4c3f-bf8c-1fcb3c5a5fcb, currentDir=/home/pazz/repo/teaching/2021-COMP122/templates/Assignment}
Attempting to read last messages from the daemon log...
Daemon pid: 2322549
  log file: /home/pazz/.gradle/daemon/6.1/daemon-2322549.out.log
----- Last  20 lines from daemon log file - daemon-2322549.out.log -----
        at com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask.createRootModule(CheckstyleAntTask.java:412)
        ... 243 more
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Property 'fileExtensions' does not exist, please check the documentation
        at com.puppycrawl.tools.checkstyle.api.AutomaticBean.tryCopyProperty(AutomaticBean.java:223)
        at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:191)
        at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:468)
        ... 245 more
--------------------------------------------------------------------------------
MP0: Location
--------------------------------------------------------------------------------
Compiler                       0    Assignment didn't compile
checkstyle                     0    checkstyle crashed
--------------------------------------------------------------------------------
Total                          0    
--------------------------------------------------------------------------------
Note that the maximum local grade is 90/100. 10 points will be awarded during
official grading if you have submitted code that earns at least 40 points by
Monday, May 20.
--------------------------------------------------------------------------------
Daemon vm is shutting down... The daemon has exited normally or was terminated in response to a user interrupt.
----- End of the daemon log -----


FAILURE: Build failed with an exception.

* What went wrong:
Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

> Task :grade
--------------------------------------------------------------------------------
MP0: Location
--------------------------------------------------------------------------------
Compiler                       0    Assignment didn't compile
checkstyle                     0    checkstyle crashed
--------------------------------------------------------------------------------
Total                          0    
--------------------------------------------------------------------------------
Note that the maximum local grade is 90/100. 10 points will be awarded during
official grading if you have submitted code that earns at least 40 points by
Monday, May 20.
--------------------------------------------------------------------------------
```

The error `Unable to create Root Module`  is exactly what I get when using an old checkstyle version on this same config.

**Comment by Fleex255** [comment]
To stop checkstyle from corrupting the Gradle process when it crashes (e.g. due to syntax errors), GradleGrader creates a new checkstyle task that is configured somewhat independently from the normal one created by the checkstyle Gradle plugin. Its version needs to be set inside the GradleGrader configuration:

```groovy
gradlegrader {
    checkstyle {
        points = 10
        configFile = file('config/checkstyle/checkstyle.xml')
        version = '8.32' // use the newest checkstyle version
    }
    // other configuration...
}
```

**Comment by pazz** [comment]
Works like a charm. Thanks again for the quick reply!
